accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from accounts.views import signup
from django.contrib.auth import views as auth_views

# from accounts import views as user_views
from accounts.views import ProfileCreateView


urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path(
        "logout/",
        LogoutView.as_view(template_name="registration/logged_out.html"),
        name="logout",
    ),
    path("signup/", signup, name="signup"),
    path("profile/", ProfileCreateView.as_view(), name="profile"),
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(
            template_name="password_reset/password_reset_form.html"
        ),
        name="password_reset",
    ),
    path(
        "password/change/done/",
        auth_views.PasswordChangeDoneView.as_view(
            template_name="password_change_done.html"
        ),
        name="password_change_done",
    ),
    # --------
    path(
        "password_change/",
        auth_views.PasswordChangeView.as_view(
            template_name="password_reset/password_change.html"
        ),
        name="password_change",
    ),
    path(
        "password_reset/done/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="password_reset/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="password_reset/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

projects/urls.py
from django.urls import path

from projects.views import (
    ProjectListView,
    ProjectCreateView,
    ProjectDetailView,
)


urlpatterns = [
    path("", ProjectListView.as_view(), name="list_projects"),
    path("create/", ProjectCreateView.as_view(), name="create_project"),
    path("<int:pk>/", ProjectDetailView.as_view(), name="show_project"),
]

tasks/urls.py
from django.urls import path

from tasks.views import TaskCreateView, TaskListView, TaskUpdateView

urlpatterns = [
    path("create/", TaskCreateView.as_view(), name="create_task"),
    path("mine/", TaskListView.as_view(), name="show_my_tasks"),
    path("<int:pk>/complete/", TaskUpdateView.as_view(), name="complete_task"),
]

tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.conf.urls.static import static
from django.conf import settings

# from accounts import views as user_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("projects/", include("projects.urls")),
    path("tasks/", include("tasks.urls")),
    path("", RedirectView.as_view(url="/projects/"), name="home"),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

accounts/models.py
from django.contrib.auth.models import User
from django.db import models


class Profile(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    bio = models.CharField(max_length=100)
    goals = models.TextField(null=True)
    image = models.ImageField(default="default.jpg", upload_to="profile_pics")

    def __str__(self):
        return str("self.user")

projects/models.py
from django.db import models

# Create your models here.


class Project(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    members = models.ManyToManyField(
        "auth.User",
        related_name="projects",
    )

    def __str__(self):
        return self.name

tasks/models.py
from django.db import models
from django.conf import settings

# Create your models here.


class Task(models.Model):
    name = models.CharField(max_length=200)
    start_date = models.DateTimeField()
    due_date = models.DateTimeField()
    is_completed = models.BooleanField(default=False)
    project = models.ForeignKey(
        "projects.Project", related_name="tasks", on_delete=models.CASCADE
    )
    assignee = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="tasks",
        on_delete=models.SET_NULL,
        null=True,
    )

    def __str__(self):
        return self.name

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

accounts/views.py
# from pyexpat.errors import messages
from django.contrib.auth import login
from django.contrib.auth.models import User

# from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
from .forms import UserRegisterForm
from accounts.models import Profile
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin


def signup(request):
    if request.method == "POST":
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            username = request.POST.get("username")
            password = request.POST.get("password1")
            user = User.objects.create_user(
                username=username,
                password=password,
            )
            user.save()
            login(request, user)
            return redirect("home")
    else:
        form = UserRegisterForm()
    context = {
        "form": form,
    }
    return render(request, "registration/signup.html", context)


# messages.success(
#    request, f"Your account has been created! Please login."


class ProfileCreateView(LoginRequiredMixin, CreateView):
    model = Profile
    template_name = "User/profile.html"
    fields = ["user", "bio", "goals", "image"]

    def get_success_url(self):
        return reverse_lazy("show_profile", args=[self.object.id])


# def profile(request):
# return render(request, 'profile.html')

projects/views.py
# from pyexpat import model
# from re import template
# from django.shortcuts import render

from projects.models import Project
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy


# Create your views here.


class ProjectCreateView(LoginRequiredMixin, CreateView):
    model = Project
    template_name = "create.html"
    fields = ["name", "description", "members"]

    # need to redirect to detail page...
    def get_success_url(self):
        return reverse_lazy("show_project", args=[self.object.id])


class ProjectListView(LoginRequiredMixin, ListView):
    model = Project
    template_name = "list.html"

    def get_queryset(self):
        return Project.objects.filter(members=self.request.user)


class ProjectDetailView(LoginRequiredMixin, DetailView):
    model = Project
    template_name = "detail.html"
    context_object_name = "project"

tasks/views.py
# Create your views here.
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView
from tasks.models import Task
from django.contrib.auth.mixins import LoginRequiredMixin


class TaskCreateView(LoginRequiredMixin, CreateView):
    model = Task
    template_name = "create_task.html"
    fields = ["name", "start_date", "due_date", "project", "assignee"]

    def get_success_url(self):
        return reverse_lazy("show_project", args=[self.object.id])


class TaskListView(LoginRequiredMixin, ListView):
    model = Task
    template_name = "list_tasks.html"

    def get_queryset(self):
        return Task.objects.filter(assignee=self.request.user)


class TaskUpdateView(LoginRequiredMixin, UpdateView):
    model = Task
    template_name = "list_tasks.html"
    fields = ["is_completed"]
    success_url = reverse_lazy("show_my_tasks")

accounts/templates/User/profile.html
{%extends 'base.html'%}
{%block content%}
<h1>My Profile</h1>

<body>
    <div>
        <ul>
            {{user.image}}
            <li>Username: {{user.username}}</li>
            <li>Firstname: {{user.firstname}}</li>
            <li>Lastname: {{user.lastname}}</li>
            <li>About Me: {{profile.bio}}</li>
            <li>Goals: {{user.goals}}</li>
        </ul>
    </div>
    <table>
        <thead>
            <tr>
                <th>Number of Projects</th>
                <th>Number of tasks</th>
            </tr>
        </thead>
        <tbody>
            {% for project in project_list %}
            <tr>
                <td>{{projects_list.all|length}}</td>
            </tr>
            {%endfor%}
            {% for project in project_list %}
            <tr>
                <td class="light"><a href="{%url 'show_project' project.id %}">{{project.name}}</a></td>
                <td>{{project.tasks.all|length}}</td>
            </tr>
            {%endfor%}
        </tbody>
    </table>
    <div>

    </div>
</body>

{%endblock content%}

accounts/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">


<head>
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Title</title>
</head>

<body>
    <header>
        <nav>
            <ul>
                <!-- 
                <li>
                    <a href="{%url 'home'%}">Home</a> 
                </li>
            -->
                {% if user.is_authenticated is True%}
                <l1>
                    <a href="{%url 'profile'%}">My Profile</a>
                </l1>
                <li>
                    <a href="{%url 'show_my_tasks'%}">My Task</a>
                </li>
                <li>
                    <a href="{%url 'list_projects'%}">My projects</a>
                </li>
                <li>
                    <a href="{%url 'logout'%}">Logout</a>
                </li>
                {%else%}
                <li>
                    <a href="{%url 'login'%}">Login</a>
                </li>
                <li>
                    <a href="{%url 'signup'%}">Signup</a>
                </li>
                {%endif%}
            </ul>

        </nav>
    </header>
    <main>

        {% block content %}

        {% endblock content %}

    </main>
</body>

</html>
<!----cursor style this places the circle in the center 
    of cursor-->
<div id="cursor">
    <script>
        var cursor = document.getElementById("cursor");
        document.onmousemove = function (e) {
            cursor.style.left = (e.pageX) + "px";
            cursor.style.top = (e.pageY) + "py";
            cursor.style.display = "block"; </script>
</div>

accounts/templates/password_reset/password_change.html
{% extends 'base.html' %}

{% block content %}



<form id="id_password_change_form" method="POST" class="form-signin">{% csrf_token %}
    <h1 class="h3 mb-3 font-weight-normal">Change password</h1>
    <input name="old_password" class="form-control" placeholder="Old password" type="password" id="id_old_password"
        required="true">
    <input name="new_password1" class="form-control" placeholder="New password" type="password" id="id_new_password1"
        required="true">
    <input name="new_password2" class="form-control" placeholder="Confirm password" type="password"
        id="id_new_password2" required="true">

    {% for field in form %}
    {% for error in field.errors %}
    <p style="color: red">{{ error }}</p>
    {% endfor %}
    {% endfor %}

    <button id="id_submit_btn" class="btn btn-lg btn-primary btn-block" type="submit">Update</button>
</form>


{% endblock %}

accounts/templates/password_reset/password_done.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <div class="d-flex flex-column">
        <p class="m-auto">Your password has been Updated.</p>
    </div>
</div>

{% endblock %}

accounts/templates/password_reset/password_reset_complete.html
{% extends 'base.html' %}


{% block content %}

<div class="container">
	<div class="d-flex flex-column">
		<p class="m-auto">Your password has been reset. You may go ahead and <a href="{% url 'login' %}">sign in</a>
			now.</p>
	</div>
</div>

{% endblock %}

accounts/templates/password_reset/password_reset_done.html
{% extends 'base.html' %}

{% block content %}

<div class="container">

    <div class="d-flex flex-column">
        <p class="m-auto p-2">
            We've emailed you instructions for resetting your password, if an account exists with the email you entered.
        </p>
        <p class="m-auto p-2">
            If you don't receive an email, please make sure you've entered the email address you registered with,
            and check your spam folder.
        </p>
        <button><a href="{% url 'home' %}">Return to Login page</a></button>
    </div>
</div>

{% endblock %}

accounts/templates/password_reset/password_reset_email.html
{% autoescape off %}
To initiate the password reset process for your Account {{ user.email }},
click the link below:

{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

If clicking the link above doesn't work, please copy and paste the URL in a new browser
window instead.

Sincerely,
The Open-Chat Team
{% endautoescape %}

accounts/templates/password_reset/password_reset_form.html
{% extends 'base.html' %}


{% block content %}


<div class="password-reset-form">
    <h1>Reset password</h1>
    <form method="POST">{% csrf_token %}
        <p>Please enter the email assoicated with your account </p>
        <input name="email" class="form-control" placeholder="Email address" type="email" id="id_email" required="true">
        <br>
        <br>
        <button>Send reset email</button>
    </form>
</div>



{% endblock %}

projects/templates/create.html
{% extends 'base.html' %}

{% block content %}
<div class="project-form">
    <h1>Create Project</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button>Create</button>
    </form>
</div>
{% endblock content %}

projects/templates/detail.html
{%extends 'base.html'%}
{% load markdownify %}



{% block content %}
<div class="project-detail">
    <h1>{{ project.name }}</h1>
    {{ project.description|markdownify }}
    <h2>Tasks</h2>
    {% if project.tasks.all %}
    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Assignee</th>
                <th>Start date</th>
                <th>Due date</th>
                <th>Is completed</th>
            </tr>
        </thead>
        <tbody>
            {%for task in project.tasks.all%}
            <tr>
                <td>{{task.name}}</td>
                <td>{{task.assignee}}</td>
                <td>{{task.start_date}}</td>
                <td>{{task.due_date}}</td>
                <td>{{task.is_completed|yesno}}</td>
            </tr>
            {%endfor%}
        </tbody>
    </table>
    {%else%}
    <p>This project has no tasks</p>
    {%endif%}
    <button>
        <a href="{%url 'create_task'%}">Create New Task</a>
    </button>
</div>
{% endblock content %}

projects/templates/list.html
{% extends 'base.html' %}

{%block content%}
<div class="project-list">
    <h1>My Projects</h1>
    <button>
        <a href="{% url 'create_project' %}">Create New Project</a>
    </button>
    {%if not project_list%}
    <p>You are not assigned to any projects</p>
    {%else%}
    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Number of task</th>
            </tr>
        </thead>
        <tbody>
            {% for project in project_list %}
            <tr>
                <td class="light"><a href="{%url 'show_project' project.id %}">{{project.name}}</a></td>
                <td>{{project.tasks.all|length}}</td>
            </tr>
            {%endfor%}
        </tbody>
    </table>
    {%endif%}
</div>
{%endblock content%}

</html>

tasks/templates/create_task.html
{% extends 'base.html' %}

{% block content %}
<div class="task-form">
    <h1>Create New Task</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button>Create</button>
    </form>
</div>
{% endblock content %}

tasks/templates/list_tasks.html
{% extends 'base.html' %}

{% block content %}
<div class="my-tasks-list">
    <h1>My Tasks</h1>
    <button>
        <a href="{% url 'create_task' %}">Create New Task</a>
    </button>
    {% if task_list %}
    <table>
        <thead>
            <th>Name</th>
            <th>Start date</th>
            <th>Due date</th>
            <th>Is completed</th>
        </thead>
        <tbody>
            {% for task in task_list %}
            <tr>
                <td>{{ task.name }}</td>
                <td>{{ task.start_date }}</td>
                <td>{{ task.due_date }}</td>
                {% if task.is_completed %}
                <td>Done</td>
                {% else %}
                <td>
                    <form method="post" action="{% url 'complete_task' task.id %}">
                        {% csrf_token %}
                        <input type="hidden" name="is_completed" value="True">
                        <button>Complete</button>
                    </form>
                </td>
                {% endif %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <p>You have no tasks</p {% endif %} {% endblock content %}